---
AllCops:
  NewCops: enable
  TargetRubyVersion: '2.6'

Layout/LineLength:
  Max: 100
  Exclude:
    - test/**/*

Metrics/AbcSize:
  Exclude:
    - examples/**/*
    - test/**/*

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/ruby-fire.rb

Naming/MethodParameterName:
  Exclude:
    - examples/**/*
    - test/**/*

Style/Documentation:
  Enabled: false

Style/OptionalArguments:
  Exclude:
    - test/**/*

Style/SpecialGlobalVars:
  Exclude:
    - examples/**/*
