---
AllCops:
  NewCops: enable
  TargetRubyVersion: '2.6'

Layout/LineLength:
  Max: 100
  Exclude:
    - test/**/*

Metrics/AbcSize:
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Safe: true

Style/OptionalArguments:
  Exclude:
    - test/**/*
